print "Starting maya loading and fbx conversion \n";
			
if (`file -q -exists "D:/Users/abw5248/GitHub/AIGE_03/3_10NavMeshAgent/Assets/free_pack/maya wolf.ma"`)
{
	file -o "D:/Users/abw5248/GitHub/AIGE_03/3_10NavMeshAgent/Assets/free_pack/maya wolf.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/Users/abw5248/GitHub/AIGE_03/3_10NavMeshAgent/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

system ("del \"D:\\Users\\abw5248\\GitHub\\AIGE_03\\3_10NavMeshAgent\\Temp\\CommandPipe\"");

$donepipeKill = `fopen "D:/Users/abw5248/GitHub/AIGE_03/3_10NavMeshAgent/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
